# Numpy 提出課題


1. Numpyについて学習します。(15問)

**<font color="red">このファイルは、コピーして自分のドライブに保存しなければ、編集が保存されず、課題を提出できません。</font>**

**<font color="red">もしまだコピーしていなければ、「事前準備」レッスンの「Chapter 2
演習問題、提出課題について」を参考にしながら、左上の「ファイル」から「ドライブにコピーを保存」を選択して、必ずコピーを保存してください。</font>**

### 1. Numpyについて学習します。(15問)

#### 1.1 「まずはNumpyをインポートし、npという名前で利用できるようにしてください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「ライブラリの読み込み方法」節
</details>

In [1]:
import numpy as np

#### 1.2 「101~150の整数を格納した、次元ごとの要素数が(10,5)である二次元配列を作成して、array_1という名前の変数に代入して表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「ndarrayの作成方法」・「ndarrrayの次元数」節
</details>

In [2]:
array_1 = np.arange(101, 151).reshape(10,5)
array_1

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145],
       [146, 147, 148, 149, 150]])

#### 1.3 「1.2と同様に、151~200の整数を格納した、次元ごとの要素数が(10,5)である二次元配列を作成して、array_2という名前の変数に代入して表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「ndarrayの作成方法」・「ndarrrayの次元数」節
</details>

In [3]:
array_2 = np.arange(151, 201).reshape(10,5)
array_2

array([[151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165],
       [166, 167, 168, 169, 170],
       [171, 172, 173, 174, 175],
       [176, 177, 178, 179, 180],
       [181, 182, 183, 184, 185],
       [186, 187, 188, 189, 190],
       [191, 192, 193, 194, 195],
       [196, 197, 198, 199, 200]])

# *1.4 「array_1の上から4行目のみを表示してください。」

---



<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「参照方法について」節
</details>

In [4]:
array_1[3,:]

array([116, 117, 118, 119, 120])

1.5 「array_2の左から3列目を表示してください。」

In [5]:
array_2[:,2]

array([153, 158, 163, 168, 173, 178, 183, 188, 193, 198])

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「参照方法について」節
</details>

#### 1.6 「array_1の上から3行目・左から4列目の数値を表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「参照方法について」節
</details>

In [6]:
array_1[2, 3]

114

#### 1.7 「array_1の上から4\~7行・左から4\~5列に含まれるような配列を表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「参照方法について」節
</details>

In [7]:
array_1[3:7, 3:5]

array([[119, 120],
       [124, 125],
       [129, 130],
       [134, 135]])

#### 1.8 「array_1の要素がそれぞれ3の倍数であるかどうかを真偽値で表した配列を作成し、変数に代入して表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「参照方法について」・「配列の論理演算方法」節
</details>

In [8]:
array_1 = np.array(array_1)
array_1 % 3 == 0

array([[False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

#### 1.9 「1.8で作成した配列を用いて、array_1の中で3の倍数である要素を格納した配列を作成し、変数に代入して表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「参照方法について」・「配列の論理演算方法」節
</details>

In [9]:
array_1_multiple_of_three = array_1[array_1 % 3 == 0]
print(array_1_multiple_of_three)


[102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150]


#### 1.10 「『array_2の要素の中で3の倍数であるもの』と同じ位置にあるarray_1の要素を格納した配列を作成し、変数に代入して表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「参照方法について」・「配列の論理演算方法」節
</details>

In [10]:
array_2_multiples_of_three = array_2[array_2 % 3 == 0]
array_1_corresponding_elements = array_1[array_2 % 3 == 0]
print(array_1_corresponding_elements)


[103 106 109 112 115 118 121 124 127 130 133 136 139 142 145 148]


#### 1.11 「array_1の要素の中で2の倍数、または5の倍数の要素を格納した配列を作成し、変数に代入して表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「参照方法について」・「配列の論理演算方法」節
</details>

In [11]:
array_1_multiple_of_two_or_five = array_1[(array_1 % 2 == 0) | (array_1 % 5 == 0)]
print(array_1_multiple_of_two_or_five)

[102 104 105 106 108 110 112 114 115 116 118 120 122 124 125 126 128 130
 132 134 135 136 138 140 142 144 145 146 148 150]


#### 1.12 「array_1とarray_2を縦に結合したような配列を作成し、表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「配列の結合・分割方法」節
</details>

In [12]:
np.concatenate([array_1, array_2],axis=0)

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145],
       [146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165],
       [166, 167, 168, 169, 170],
       [171, 172, 173, 174, 175],
       [176, 177, 178, 179, 180],
       [181, 182, 183, 184, 185],
       [186, 187, 188, 189, 190],
       [191, 192, 193, 194, 195],
       [196, 197, 198, 199, 200]])

#### 1.13 「array_1とarray_2を横に結合したような配列を作成し、表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「配列の結合・分割方法」節
</details>

In [13]:
array = np.concatenate([array_1, array_2],axis=1)
print(array)

[[101 102 103 104 105 151 152 153 154 155]
 [106 107 108 109 110 156 157 158 159 160]
 [111 112 113 114 115 161 162 163 164 165]
 [116 117 118 119 120 166 167 168 169 170]
 [121 122 123 124 125 171 172 173 174 175]
 [126 127 128 129 130 176 177 178 179 180]
 [131 132 133 134 135 181 182 183 184 185]
 [136 137 138 139 140 186 187 188 189 190]
 [141 142 143 144 145 191 192 193 194 195]
 [146 147 148 149 150 196 197 198 199 200]]






#### 1.14 「array_1とarray_2を上下に2つに分解したような二つの配列を表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「配列の結合・分割方法」節
</details>

In [ ]:
#old answer
combined_array = np.vstack((array_1, array_2))
array_split = np.vsplit(combined_array, 2)
display(array_split[0])
display(array_split[1])

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145],
       [146, 147, 148, 149, 150]])

array([[151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165],
       [166, 167, 168, 169, 170],
       [171, 172, 173, 174, 175],
       [176, 177, 178, 179, 180],
       [181, 182, 183, 184, 185],
       [186, 187, 188, 189, 190],
       [191, 192, 193, 194, 195],
       [196, 197, 198, 199, 200]])

In [15]:
#new answer
np.vsplit(array_1, 2)
np.vsplit(array_2, 2)

[array([[151, 152, 153, 154, 155],
        [156, 157, 158, 159, 160],
        [161, 162, 163, 164, 165],
        [166, 167, 168, 169, 170],
        [171, 172, 173, 174, 175]]),
 array([[176, 177, 178, 179, 180],
        [181, 182, 183, 184, 185],
        [186, 187, 188, 189, 190],
        [191, 192, 193, 194, 195],
        [196, 197, 198, 199, 200]])]

#### 1.15 「array_2の各列の最小値を表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「配列の統計量計算方法」節
</details>

In [ ]:
array_2 = np.array(array_2)
np.min(array_2, axis=0)

array([151, 152, 153, 154, 155])

#### 1.16 「array_1の要素の中で3の倍数であるものの数をカウントして、表示してください。」

<details>
<summary>
この問題に関連する内容を復習するためのスライド
</summary>

Numpyの「その他よく使用するメソッド」節
</details>

In [ ]:
array_1 = np.array(array_1)
np.count_nonzero(array_1 % 3 == 0)

17